name: flutter_quote
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  bloc: null
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  equatable: ^2.0.7
  floor: ^1.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.3
  hive_flutter: ^1.1.0
  retrofit: ^4.4.1
  share_plus: ^10.1.3

dev_dependencies:
  build_runner: ^2.4.14
  floor_generator: ^1.5.0

  flutter_lints: ^4.0.0
  # json_serializable: ^6.9.2
  flutter_test:
    sdk: flutter
  retrofit_generator: ^9.1.5
flutter:
  uses-material-design: true
